# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 556e5995d4ba3655d7b39ee852adc57ad171d1d7dc6a774b43c7560ccc08ae93faa95485608e663d4c7005c1e35b123509181bebc2ba7f3f5d3fd406538265c0

test:
  secret_key_base: 4b723954cc2e65a915f33b48e7c514da0c27df58fd979fde9e8dd53490d9ebb703e8cd0e726ad138de328fe702b060b7e01d0da8f7859f72bb7dcc5184b66e95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
